language: cpp
script:
  - autoreconf --force --install && ./configure
  - make && make check
after_success:
  - make clean
  - make CXXFLAGS='-coverage -O0' && make check
  - ./codecov
  - bash <(curl -s https://codecov.io/bash)
